### ISSUE TITLE
Wrong answers

### ISSUE THREAD

**Issue by fabio-escanfella** [Ditectrev/Professional-Scrum-Product-Owner-PSPO-I-Practice-Tests-Exams-Questions-Answers#1]
Hi there, GREAT job on all of these questions and answers. Thanks a lot!

These are the following answers I found Mistakes. I hope it helps! :)

127 - To create focus which of the following are most important to have ready when Sprint Planning begins? (choose the best two answers)
Wrong: "A clear and non-negotiable Sprint Goal." (the sprint goal should be discussed with the scrum team)
Should be: "A Product Goal communicated by the Product Owner." 
   - This gives the Scrum Team a clear direction and understanding of what they are aiming to achieve in the product increment resulting from the upcoming Sprint.

226- Which two of the following are typical Daily Scrum outcomes?
Wrong: "Impediments identified by the Scrum Master." (SM doesn't even have to attend Daily Scrum)
Should be: "A refined Daily Backlog." 
   - During the Daily Scrum, the Developers plan the work for the next 24 hours. This often results in the refinement or updating of the Sprint Backlog, based on the discussions and decisions made.

250- In the middle of the Sprint, the customer decides that there are two new features she wants. The Product Owner could: (choose the best two answers)
Wrong: "Introduce these features at the next Daily Scrum." (The primary function of the Daily Scrum is to inspect the work done since the last meeting and plan the work for the next 24 hours, not to introduce new work)
Wrong: "Have the Scrum Master add these features to the current Sprint." (SM is not responsible for adding features)
Should be: "Ask the Developers to consider whether they can add these features to the current Sprint without endangering the Sprint Goal." 
   - In Scrum, changes are welcomed, but they should not disrupt the current Sprint's work, and the Developers should make the decision if it is feasible to include these changes without endangering the Sprint Goal.
Should be: "Add these features to the Product Backlog." 
   - This is the most appropriate action. Any new requirements or features should be added to the Product Backlog and then they can be ordered and refined for consideration in future Sprints.

252 - When the Developers determine that they will not be able to finish the complete forecast, who needs to be present when reviewing and adjusting the Sprint work selected? (choose the best answer)
Wrong: "The Scrum Master and the Developers."
Should be: "The Product Owner and the Developers."
   - The Product Owner is responsible for maximizing the value of the product and the work of the Developers. Therefore, the Product Owner should be involved in the discussion when it becomes apparent that the team won't be able to complete the forecasted work. The Scrum Master's role is to help the team follow Scrum practices and principles, but they don't need to be involved in every discussion about the work, and certainly not the operational decisions about how to adjust the scope of a Sprint.

258 - When multiple Scrum Teams are working on the same product, should all of their Increments be integrated every Sprint? (choose the best answer)
Wrong:  Yes, but only for Scrum Teams whose work has dependencies.
Should be: "Yes, in order to accurately inspect what is done."
   - When multiple Scrum Teams are working on the same product, their work should be integrated into one Increment every Sprint. This is to ensure that the product is in a potentially shippable state at the end of each Sprint, which is a fundamental aspect of Scrum. This approach provides transparency and enables inspection of the integrated product at the end of each Sprint, regardless of team dependencies. It also minimizes integration risks and enables early discovery of integration issues or inconsistencies across teams.

262 - Who owns the Sprint Backlog? (choose the best answer)
Wrong:  "The Scrum Team."
Should be: "The Developers."
   - The Developers are the ones who craft and manage the Sprint Backlog. They're responsible for selecting the items from the Product Backlog to work on during the Sprint, as well as updating the Sprint Backlog throughout the Sprint as work is completed and new information is discovered. While the Product Owner, Scrum Master, and other stakeholders may have input, the ultimate authority over the Sprint Backlog belongs to the Developers.

That's it. 258 and 262 I'm not 100% sure, but I think the rationale above is correct. 

I'm open to any answer discussion. I hope it helps the community! :)

**Comment by svenrr** [comment]
Hi, 
what about #25? 

**Why would you expect a Product Owner to care that the Scrum Team adheres to its Definition of Done? (choose the best two answers)**
[]To be able to punish the team when they do not meet their velocity goal for the Sprint.
[]The Product Owner should not care about the Definition of Done, it is the Scrum Team's responsibility.
[x]The Definition of Done can affect the product's total cost of ownership. **--> Should be correct?**
[x]To have complete transparency into what has been done at the end of each Sprint.
[]To forecast the team's productivity over time. **--> Should be wrong?**

**Comment by danieldanielecki** [comment]
@fabio-escanfella @svenrr, let me research!

**Comment by svenrr** [comment]
#223

**A Scrum Team is a cohesive unit of professionals that consists of which of the following? (choose all that apply)**
- One Product Owner (is missing!)
- One Scrum Master
- Developers

**Comment by svenrr** [comment]
#257 

**The job of a Product Owner focuses on the following: (choose the best two answers)**
-  Clearly communicating project or release status and strategies to customers and stakeholders. **-> correct**
-  Working with customers and stakeholders to identify the most valuable product requirements. **-> correct**
-  Being with the Scrum Team all the time, just in case they need me to clarify a requirement. **-> wrong**
-  Writing clear, transparent User Stories. **-> wrong**

**Comment by fabio-escanfella** [comment]
> **Why would you expect a Product Owner to care that the Scrum Team adheres to its Definition of Done? (choose the best two answers)**
> []To be able to punish the team when they do not meet their velocity goal for the Sprint.
> []The Product Owner should not care about the Definition of Done, it is the Scrum Team's responsibility.
> [x]The Definition of Done can affect the product's total cost of ownership. **--> Should be correct?**
> [x]To have complete transparency into what has been done at the end of each Sprint.
> []To forecast the team's productivity over time.

Yes, I agree with you, @svenrr 

 "To forecast the team's productivity over time." - While the Definition of Done can help ensure consistency, it's not primarily a tool for forecasting productivity. It's more about ensuring quality and completeness of the work done. (so in my opinion, should be wrong)
 
 "The Definition of Done can affect the product's total cost of ownership."  If items are marked as done but are not truly complete according to the Definition of Done, it could lead to additional work or defects in the future, which can increase the total cost of ownership of the product. (so in my opinion, should be right)

**Comment by fabio-escanfella** [comment]
> 

Yes, you are right, it's missing. But for me here this is question number 253.

**Comment by fabio-escanfella** [comment]
> #223
> 
> **A Scrum Team is a cohesive unit of professionals that consists of which of the following? (choose all that apply)**
> 
> * One Product Owner (is missing!)
> * One Scrum Master
> * Developers


Yes, you are right, it's missing. But for me here this is question number 253.

**Comment by fabio-escanfella** [comment]
> #257
> 
> **The job of a Product Owner focuses on the following: (choose the best two answers)**
> 
> * Clearly communicating project or release status and strategies to customers and stakeholders. **-> correct**
> * Working with customers and stakeholders to identify the most valuable product requirements. **-> correct**
> * Being with the Scrum Team all the time, just in case they need me to clarify a requirement. **-> wrong**
> * Writing clear, transparent User Stories. **-> wrong**


Well, this is questionable, but I answered the same as you. 

"Clearly communicating project or release status and strategies to customers and stakeholders." - The Product Owner is responsible for managing stakeholders' expectations, communicating progress, and strategizing about product releases. 

"Writing clear, transparent User Stories." - While this is often a task the Product Owner may perform, it is not a specific focus or requirement of the role according to Scrum Guide. The format of Product Backlog Items (whether they are written as user stories, use cases, etc.) is not prescribed in Scrum. (so in my opinion, it should be wrong and the previous right)

**Comment by danieldanielecki** [comment]
> #223
> 
> **A Scrum Team is a cohesive unit of professionals that consists of which of the following? (choose all that apply)**
> 
> * One Product Owner (is missing!)
> * One Scrum Master
> * Developers

That's correct, fixed in https://github.com/Ditectrev/Professional-Scrum-Product-Owner-PSPO-I-Practice-Tests-Exams-Questions-Answers/commit/ce1fbd7d3130025d6d38919f8576a7165ed02142, and yes @fabio-escanfella, the question is 253, it must have been a typo from @svenrr side.

**Comment by danieldanielecki** [comment]
> #257
> 
> **The job of a Product Owner focuses on the following: (choose the best two answers)**
> 
> * Clearly communicating project or release status and strategies to customers and stakeholders. **-> correct**
> * Working with customers and stakeholders to identify the most valuable product requirements. **-> correct**
> * Being with the Scrum Team all the time, just in case they need me to clarify a requirement. **-> wrong**
> * Writing clear, transparent User Stories. **-> wrong**

Also correct feedback, fixed in https://github.com/Ditectrev/Professional-Scrum-Product-Owner-PSPO-I-Practice-Tests-Exams-Questions-Answers/commit/80f3cd0dace47375f29cc1bfb7eceb5091411fa7.

**Comment by svenrr** [comment]
Regarding #127:
I'd say that the Sprint Goal is created during the Sprint Planning by the Scrum Team, therefore it's impossible that is already created beforehand.

**Comment by danieldanielecki** [comment]
Sorry, I've confused terminologies. Of course, that's correct.
Q127 was fixed in https://github.com/Ditectrev/Professional-Scrum-Product-Owner-PSPO-I-Practice-Tests-Exams-Questions-Answers/commit/57a1bc4d7429033f3c06f6cd336ea75fe57c6e7b.

**Comment by danieldanielecki** [comment]
@fabio-escanfella, regarding question 226 - where did you find such a term as `Daily Backlog`?

**Comment by danieldanielecki** [comment]
> Hi there, GREAT job on all of these questions and answers. Thanks a lot!
> 
> These are the following answers I found Mistakes. I hope it helps! :)
> 
> 127 - To create focus which of the following are most important to have ready when Sprint Planning begins? (choose the best two answers) Wrong: "A clear and non-negotiable Sprint Goal." (the sprint goal should be discussed with the scrum team) Should be: "A Product Goal communicated by the Product Owner."
> 
> * This gives the Scrum Team a clear direction and understanding of what they are aiming to achieve in the product increment resulting from the upcoming Sprint.
> 
> 226- Which two of the following are typical Daily Scrum outcomes? Wrong: "Impediments identified by the Scrum Master." (SM doesn't even have to attend Daily Scrum) Should be: "A refined Daily Backlog."
> 
> * During the Daily Scrum, the Developers plan the work for the next 24 hours. This often results in the refinement or updating of the Sprint Backlog, based on the discussions and decisions made.
> 
> 250- In the middle of the Sprint, the customer decides that there are two new features she wants. The Product Owner could: (choose the best two answers) Wrong: "Introduce these features at the next Daily Scrum." (The primary function of the Daily Scrum is to inspect the work done since the last meeting and plan the work for the next 24 hours, not to introduce new work) Wrong: "Have the Scrum Master add these features to the current Sprint." (SM is not responsible for adding features) Should be: "Ask the Developers to consider whether they can add these features to the current Sprint without endangering the Sprint Goal."
> 
> * In Scrum, changes are welcomed, but they should not disrupt the current Sprint's work, and the Developers should make the decision if it is feasible to include these changes without endangering the Sprint Goal.
>   Should be: "Add these features to the Product Backlog."
> * This is the most appropriate action. Any new requirements or features should be added to the Product Backlog and then they can be ordered and refined for consideration in future Sprints.
> 
> 252 - When the Developers determine that they will not be able to finish the complete forecast, who needs to be present when reviewing and adjusting the Sprint work selected? (choose the best answer) Wrong: "The Scrum Master and the Developers." Should be: "The Product Owner and the Developers."
> 
> * The Product Owner is responsible for maximizing the value of the product and the work of the Developers. Therefore, the Product Owner should be involved in the discussion when it becomes apparent that the team won't be able to complete the forecasted work. The Scrum Master's role is to help the team follow Scrum practices and principles, but they don't need to be involved in every discussion about the work, and certainly not the operational decisions about how to adjust the scope of a Sprint.
> 
> 258 - When multiple Scrum Teams are working on the same product, should all of their Increments be integrated every Sprint? (choose the best answer) Wrong: Yes, but only for Scrum Teams whose work has dependencies. Should be: "Yes, in order to accurately inspect what is done."
> 
> * When multiple Scrum Teams are working on the same product, their work should be integrated into one Increment every Sprint. This is to ensure that the product is in a potentially shippable state at the end of each Sprint, which is a fundamental aspect of Scrum. This approach provides transparency and enables inspection of the integrated product at the end of each Sprint, regardless of team dependencies. It also minimizes integration risks and enables early discovery of integration issues or inconsistencies across teams.
> 
> 262 - Who owns the Sprint Backlog? (choose the best answer) Wrong: "The Scrum Team." Should be: "The Developers."
> 
> * The Developers are the ones who craft and manage the Sprint Backlog. They're responsible for selecting the items from the Product Backlog to work on during the Sprint, as well as updating the Sprint Backlog throughout the Sprint as work is completed and new information is discovered. While the Product Owner, Scrum Master, and other stakeholders may have input, the ultimate authority over the Sprint Backlog belongs to the Developers.
> 
> That's it. 258 and 262 I'm not 100% sure, but I think the rationale above is correct.
> 
> I'm open to any answer discussion. I hope it helps the community! :)

Question250 - 100% correct & fixed in https://github.com/Ditectrev/Professional-Scrum-Product-Owner-PSPO-I-Practice-Tests-Exams-Questions-Answers/commit/0bf3155fd5b39b55b98652b71270409e1e039d0b.

**Comment by danieldanielecki** [comment]
> When the Developers determine that they will not be able to finish the co

252 - yes, fixed in https://github.com/Ditectrev/Professional-Scrum-Product-Owner-PSPO-I-Practice-Tests-Exams-Questions-Answers/commit/f0e6d917f152dd87281264089701ccdbd6ba4c96.

**Comment by danieldanielecki** [comment]
> Hi there, GREAT job on all of these questions and answers. Thanks a lot!
> 
> These are the following answers I found Mistakes. I hope it helps! :)
> 
> 127 - To create focus which of the following are most important to have ready when Sprint Planning begins? (choose the best two answers) Wrong: "A clear and non-negotiable Sprint Goal." (the sprint goal should be discussed with the scrum team) Should be: "A Product Goal communicated by the Product Owner."
> 
> * This gives the Scrum Team a clear direction and understanding of what they are aiming to achieve in the product increment resulting from the upcoming Sprint.
> 
> 226- Which two of the following are typical Daily Scrum outcomes? Wrong: "Impediments identified by the Scrum Master." (SM doesn't even have to attend Daily Scrum) Should be: "A refined Daily Backlog."
> 
> * During the Daily Scrum, the Developers plan the work for the next 24 hours. This often results in the refinement or updating of the Sprint Backlog, based on the discussions and decisions made.
> 
> 250- In the middle of the Sprint, the customer decides that there are two new features she wants. The Product Owner could: (choose the best two answers) Wrong: "Introduce these features at the next Daily Scrum." (The primary function of the Daily Scrum is to inspect the work done since the last meeting and plan the work for the next 24 hours, not to introduce new work) Wrong: "Have the Scrum Master add these features to the current Sprint." (SM is not responsible for adding features) Should be: "Ask the Developers to consider whether they can add these features to the current Sprint without endangering the Sprint Goal."
> 
> * In Scrum, changes are welcomed, but they should not disrupt the current Sprint's work, and the Developers should make the decision if it is feasible to include these changes without endangering the Sprint Goal.
>   Should be: "Add these features to the Product Backlog."
> * This is the most appropriate action. Any new requirements or features should be added to the Product Backlog and then they can be ordered and refined for consideration in future Sprints.
> 
> 252 - When the Developers determine that they will not be able to finish the complete forecast, who needs to be present when reviewing and adjusting the Sprint work selected? (choose the best answer) Wrong: "The Scrum Master and the Developers." Should be: "The Product Owner and the Developers."
> 
> * The Product Owner is responsible for maximizing the value of the product and the work of the Developers. Therefore, the Product Owner should be involved in the discussion when it becomes apparent that the team won't be able to complete the forecasted work. The Scrum Master's role is to help the team follow Scrum practices and principles, but they don't need to be involved in every discussion about the work, and certainly not the operational decisions about how to adjust the scope of a Sprint.
> 
> 258 - When multiple Scrum Teams are working on the same product, should all of their Increments be integrated every Sprint? (choose the best answer) Wrong: Yes, but only for Scrum Teams whose work has dependencies. Should be: "Yes, in order to accurately inspect what is done."
> 
> * When multiple Scrum Teams are working on the same product, their work should be integrated into one Increment every Sprint. This is to ensure that the product is in a potentially shippable state at the end of each Sprint, which is a fundamental aspect of Scrum. This approach provides transparency and enables inspection of the integrated product at the end of each Sprint, regardless of team dependencies. It also minimizes integration risks and enables early discovery of integration issues or inconsistencies across teams.
> 
> 262 - Who owns the Sprint Backlog? (choose the best answer) Wrong: "The Scrum Team." Should be: "The Developers."
> 
> * The Developers are the ones who craft and manage the Sprint Backlog. They're responsible for selecting the items from the Product Backlog to work on during the Sprint, as well as updating the Sprint Backlog throughout the Sprint as work is completed and new information is discovered. While the Product Owner, Scrum Master, and other stakeholders may have input, the ultimate authority over the Sprint Backlog belongs to the Developers.
> 
> That's it. 258 and 262 I'm not 100% sure, but I think the rationale above is correct.
> 
> I'm open to any answer discussion. I hope it helps the community! :)

258 - you're correct, fixed in https://github.com/Ditectrev/Professional-Scrum-Product-Owner-PSPO-I-Practice-Tests-Exams-Questions-Answers/commit/6bdd15d7c650218d7f720077e5ccb62eb8a625d9.

**Comment by danieldanielecki** [comment]
> Hi there, GREAT job on all of these questions and answers. Thanks a lot!
> 
> These are the following answers I found Mistakes. I hope it helps! :)
> 
> 127 - To create focus which of the following are most important to have ready when Sprint Planning begins? (choose the best two answers) Wrong: "A clear and non-negotiable Sprint Goal." (the sprint goal should be discussed with the scrum team) Should be: "A Product Goal communicated by the Product Owner."
> 
> * This gives the Scrum Team a clear direction and understanding of what they are aiming to achieve in the product increment resulting from the upcoming Sprint.
> 
> 226- Which two of the following are typical Daily Scrum outcomes? Wrong: "Impediments identified by the Scrum Master." (SM doesn't even have to attend Daily Scrum) Should be: "A refined Daily Backlog."
> 
> * During the Daily Scrum, the Developers plan the work for the next 24 hours. This often results in the refinement or updating of the Sprint Backlog, based on the discussions and decisions made.
> 
> 250- In the middle of the Sprint, the customer decides that there are two new features she wants. The Product Owner could: (choose the best two answers) Wrong: "Introduce these features at the next Daily Scrum." (The primary function of the Daily Scrum is to inspect the work done since the last meeting and plan the work for the next 24 hours, not to introduce new work) Wrong: "Have the Scrum Master add these features to the current Sprint." (SM is not responsible for adding features) Should be: "Ask the Developers to consider whether they can add these features to the current Sprint without endangering the Sprint Goal."
> 
> * In Scrum, changes are welcomed, but they should not disrupt the current Sprint's work, and the Developers should make the decision if it is feasible to include these changes without endangering the Sprint Goal.
>   Should be: "Add these features to the Product Backlog."
> * This is the most appropriate action. Any new requirements or features should be added to the Product Backlog and then they can be ordered and refined for consideration in future Sprints.
> 
> 252 - When the Developers determine that they will not be able to finish the complete forecast, who needs to be present when reviewing and adjusting the Sprint work selected? (choose the best answer) Wrong: "The Scrum Master and the Developers." Should be: "The Product Owner and the Developers."
> 
> * The Product Owner is responsible for maximizing the value of the product and the work of the Developers. Therefore, the Product Owner should be involved in the discussion when it becomes apparent that the team won't be able to complete the forecasted work. The Scrum Master's role is to help the team follow Scrum practices and principles, but they don't need to be involved in every discussion about the work, and certainly not the operational decisions about how to adjust the scope of a Sprint.
> 
> 258 - When multiple Scrum Teams are working on the same product, should all of their Increments be integrated every Sprint? (choose the best answer) Wrong: Yes, but only for Scrum Teams whose work has dependencies. Should be: "Yes, in order to accurately inspect what is done."
> 
> * When multiple Scrum Teams are working on the same product, their work should be integrated into one Increment every Sprint. This is to ensure that the product is in a potentially shippable state at the end of each Sprint, which is a fundamental aspect of Scrum. This approach provides transparency and enables inspection of the integrated product at the end of each Sprint, regardless of team dependencies. It also minimizes integration risks and enables early discovery of integration issues or inconsistencies across teams.
> 
> 262 - Who owns the Sprint Backlog? (choose the best answer) Wrong: "The Scrum Team." Should be: "The Developers."
> 
> * The Developers are the ones who craft and manage the Sprint Backlog. They're responsible for selecting the items from the Product Backlog to work on during the Sprint, as well as updating the Sprint Backlog throughout the Sprint as work is completed and new information is discovered. While the Product Owner, Scrum Master, and other stakeholders may have input, the ultimate authority over the Sprint Backlog belongs to the Developers.
> 
> That's it. 258 and 262 I'm not 100% sure, but I think the rationale above is correct.
> 
> I'm open to any answer discussion. I hope it helps the community! :)

and lastly 262, again correct - fixed in https://github.com/Ditectrev/Professional-Scrum-Product-Owner-PSPO-I-Practice-Tests-Exams-Questions-Answers/commit/9b8c0865f005fb3ed97137daf81a13546bc206b5.

**Comment by danieldanielecki** [comment]
only 226 is unclear then, remaining questions have been addressed & fixed

**Comment by danieldanielecki** [comment]
I'm closing this issue, we fixed everything excluding `226` as that one isn't clear, please open another issue if you'll be here again:)

**Comment by danieldanielecki** [comment]
> Why would you expect a Product Owner to ca

Almost missed, fixed in https://github.com/Ditectrev/Professional-Scrum-Product-Owner-PSPO-I-Practice-Tests-Exams-Questions-Answers/commit/be07d37dcc1c8c80304614e3a37ad2f9b913cfb5.
