### ISSUE TITLE
Creating a new application

### ISSUE THREAD

**Issue by batuhancengiz** [Ditectrev/Professional-Scrum-Product-Owner-PSPO-I-Practice-Tests-Exams-Questions-Answers#5]
I've created new application to read your ReadMe.md file and convert to real exam application. Maybe you guys want to try it!

Just download the ExamGenerator_v1.0.0.zip and import md files to the application.

https://github.com/batuhancengiz/ExamGenerator/releases/tag/v1.0.0
https://github.com/batuhancengiz/ExamGenerator/releases/download/v1.0.0/ExamGenerator_v1.0.0.zip

**Comment by danieldanielecki** [comment]
@batuhancengiz can you please share some screenshots / video in that repository how it works?

**Comment by batuhancengiz** [comment]
chat will continue this link-> 

https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/issues/33
